export const seriesActionTypes = {
  FETCH_WOOZEEE_SERIES_REQUEST: "FETCH_WOOZEEE_SERIES_REQUEST",
  FETCH_WOOZEEE_SERIES_SUCCESS: "FETCH_WOOZEEE_SERIES_SUCCESS",
  FETCH_WOOZEEE_SERIES_FAILURE: "FETCH_WOOZEEE_SERIES_FAILURE",
  LOAD_MORE_WOOZEEE_SERIES_SUCCESS: "LOAD_MORE_WOOZEEE_SERIES_SUCCESS",

  FETCH_TOP_TEN_SERIES_REQUEST: "FETCH_TOP_TEN_SERIES_REQUEST",
  FETCH_TOP_TEN_SERIES_SUCCESS: "FETCH_TOP_TEN_SERIES_SUCCESS",
  FETCH_TOP_TEN_SERIES_FAILURE: "FETCH_TOP_TEN_SERIES_FAILURE",
  LOAD_MORE_TOP_TEN_SERIES_SUCCESS: "LOAD_MORE_TOP_TEN_SERIES_SUCCESS",

  FETCH_ANIMATION_SERIES_REQUEST: "FETCH_ANIMATION_SERIES_REQUEST",
  FETCH_ANIMATION_SERIES_SUCCESS: "FETCH_ANIMATION_SERIES_SUCCESS",
  FETCH_ANIMATION_SERIES_FAILURE: "FETCH_ANIMATION_SERIES_FAILURE",
  LOAD_MORE_ANIMATION_SERIES_SUCCESS: "LOAD_MORE_ANIMATION_SERIES_SUCCESS",

  FETCH_COMING_SOON_SERIES_REQUEST: "FETCH_COMING_SOON_SERIES_REQUEST",
  FETCH_COMING_SOON_SERIES_SUCCESS: "FETCH_COMING_SOON_SERIES_SUCCESS",
  FETCH_COMING_SOON_SERIES_FAILURE: "FETCH_COMING_SOON_SERIES_FAILURE",
  LOAD_MORE_COMING_SOON_SERIES_SUCCESS: "LOAD_MORE_COMING_SOON_SERIES_SUCCESS",

  FETCH_CRIME_SERIES_REQUEST: "FETCH_CRIME_SERIES_REQUEST",
  FETCH_CRIME_SERIES_SUCCESS: "FETCH_CRIME_SERIES_SUCCESS",
  FETCH_CRIME_SERIES_FAILURE: "FETCH_CRIME_SERIES_FAILURE",
  LOAD_MORE_CRIME_SERIES_SUCCESS: "LOAD_MORE_CRIME_SERIES_SUCCESS",

  FETCH_RECOMMENDED_SERIES_REQUEST: "FETCH_RECOMMENDED_SERIES_REQUEST",
  FETCH_RECOMMENDED_SERIES_SUCCESS: "FETCH_RECOMMENDED_SERIES_SUCCESS",
  FETCH_RECOMMENDED_SERIES_FAILURE: "FETCH_RECOMMENDED_SERIES_FAILURE",
  LOAD_MORE_RECOMMENDED_SERIES_SUCCESS: "LOAD_MORE_RECOMMENDED_SERIES_SUCCESS",

  FETCH_FEATURED_SERIES_REQUEST: "FETCH_FEATURED_SERIES_REQUEST",
  FETCH_FEATURED_SERIES_SUCCESS: "FETCH_FEATURED_SERIES_SUCCESS",
  FETCH_FEATURED_SERIES_FAILURE: "FETCH_FEATURED_SERIES_FAILURE",
  LOAD_MORE_FEATURED_SERIES_SUCCESS: "LOAD_MORE_FEATURED_SERIES_SUCCESS",

  FETCH_KIDS_SERIES_REQUEST: "FETCH_KIDS_SERIES_REQUEST",
  FETCH_KIDS_SERIES_SUCCESS: "FETCH_KIDS_SERIES_SUCCESS",
  FETCH_KIDS_SERIES_FAILURE: "FETCH_KIDS_SERIES_FAILURE",
  LOAD_MORE_KIDS_SERIES_SUCCESS: "LOAD_MORE_KIDS_SERIES_SUCCESS",

  FETCH_SCIFIFANTASY_SERIES_REQUEST: "FETCH_SCIFIFANTASY_SERIES_REQUEST",
  FETCH_SCIFIFANTASY_SERIES_SUCCESS: "FETCH_SCIFIFANTASY_SERIES_SUCCESS",
  FETCH_SCIFIFANTASY_SERIES_FAILURE: "FETCH_SCIFIFANTASY_SERIES_FAILURE",
  LOAD_MORE_SCIFIFANTASY_SERIES_SUCCESS:
    "LOAD_MORE_SCIFIFANTASY_SERIES_SUCCESS",

  FETCH_TRENDING_SERIES_REQUEST: "FETCH_TRENDING_SERIES_REQUEST",
  FETCH_TRENDING_SERIES_SUCCESS: "FETCH_TRENDING_SERIES_SUCCESS",
  FETCH_TRENDING_SERIES_FAILURE: "FETCH_TRENDING_SERIES_FAILURE",
  LOAD_MORE_TRENDING_SERIES_SUCCESS: "LOAD_MORE_TRENDING_SERIES_SUCCESS",
};
