export const moviesActionTypes = {
  FETCH_RECOMMENDED_MOVIES_REQUEST: "FETCH_RECOMMENDED_MOVIES_REQUEST",
  FETCH_RECOMMENDED_MOVIES_SUCCESS: "FETCH_RECOMMENDED_MOVIES_SUCCESS",
  FETCH_RECOMMENDED_MOVIES_FAILURE: "FETCH_RECOMMENDED_MOVIES_FAILURE",
  LOAD_MORE_RECOMMENDED_MOVIES_SUCCESS: "LOAD_MORE_RECOMMENDED_MOVIES_SUCCESS",

  FETCH_ADVENTURE_MOVIES_REQUEST: "FETCH_ADVENTURE_MOVIES_REQUEST",
  FETCH_ADVENTURE_MOVIES_SUCCESS: "FETCH_ADVENTURE_MOVIES_SUCCESS",
  FETCH_ADVENTURE_MOVIES_FAILURE: "FETCH_ADVENTURE_MOVIES_FAILURE",
  LOAD_MORE_ADVENTURE_MOVIES_SUCCESS: "LOAD_MORE_ADVENTURE_MOVIES_SUCCESS",

  FETCH_ANIMATION_MOVIES_REQUEST: "FETCH_ANIMATION_MOVIES_REQUEST",
  FETCH_ANIMATION_MOVIES_SUCCESS: "FETCH_ANIMATION_MOVIES_SUCCESS",
  FETCH_ANIMATION_MOVIES_FAILURE: "FETCH_ANIMATION_MOVIES_FAILURE",
  LOAD_MORE_ANIMATION_MOVIES_SUCCESS: "LOAD_MORE_ANIMATION_MOVIES_SUCCESS",

  FETCH_COMING_SOON_MOVIES_REQUEST: "FETCH_COMING_SOON_MOVIES_REQUEST",
  FETCH_COMING_SOON_MOVIES_SUCCESS: "FETCH_COMING_SOON_MOVIES_SUCCESS",
  FETCH_COMING_SOON_MOVIES_FAILURE: "FETCH_COMING_SOON_MOVIES_FAILURE",
  LOAD_MORE_COMING_SOON_MOVIES_SUCCESS: "LOAD_MORE_COMING_SOON_MOVIES_SUCCESS",

  FETCH_HORROR_MOVIES_REQUEST: "FETCH_HORROR_MOVIES_REQUEST",
  FETCH_HORROR_MOVIES_SUCCESS: "FETCH_HORROR_MOVIES_SUCCESS",
  FETCH_HORROR_MOVIES_FAILURE: "FETCH_HORROR_MOVIES_FAILURE",
  LOAD_MORE_HORROR_MOVIES_SUCCESS: "LOAD_MORE_HORROR_MOVIES_SUCCESS",

  FETCH_WOOZEEE_MOVIES_REQUEST: "FETCH_WOOZEEE_MOVIES_REQUEST",
  FETCH_WOOZEEE_MOVIES_SUCCESS: "FETCH_WOOZEEE_MOVIES_SUCCESS",
  FETCH_WOOZEEE_MOVIES_FAILURE: "FETCH_WOOZEEE_MOVIES_FAILURE",
  LOAD_MORE_WOOZEEE_MOVIES_SUCCESS: "LOAD_MORE_WOOZEEE_MOVIES_SUCCESS",

  FETCH_ROMANCE_MOVIES_REQUEST: "FETCH_ROMANCE_MOVIES_REQUEST",
  FETCH_ROMANCE_MOVIES_SUCCESS: "FETCH_ROMANCE_MOVIES_SUCCESS",
  FETCH_ROMANCE_MOVIES_FAILURE: "FETCH_ROMANCE_MOVIES_FAILURE",
  LOAD_MORE_ROMANCE_MOVIES_SUCCESS: "LOAD_MORE_ROMANCE_MOVIES_SUCCESS",

  FETCH_TOP_RATED_MOVIES_REQUEST: "FETCH_TOP_RATED_MOVIES_REQUEST",
  FETCH_TOP_RATED_MOVIES_SUCCESS: "FETCH_TOP_RATED_MOVIES_SUCCESS",
  FETCH_TOP_RATED_MOVIES_FAILURE: "FETCH_TOP_RATED_MOVIES_FAILURE",
  LOAD_MORE_TOP_RATED_MOVIES_SUCCESS: "LOAD_MORE_TOP_RATED_MOVIES_SUCCESS",

  FETCH_TRENDING_MOVIES_REQUEST: "FETCH_TRENDING_MOVIES_REQUEST",
  FETCH_TRENDING_MOVIES_SUCCESS: "FETCH_TRENDING_MOVIES_SUCCESS",
  FETCH_TRENDING_MOVIES_FAILURE: "FETCH_TRENDING_MOVIES_FAILURE",
  LOAD_MORE_TRENDING_MOVIES_SUCCESS: "LOAD_MORE_TRENDING_MOVIES_SUCCESS",

  FETCH_MY_LIST_REQUEST: "FETCH_MY_LIST_REQUEST",
  FETCH_MY_LIST_SUCCESS: "FETCH_MY_LIST_SUCCESS",
  FETCH_MY_LIST_FAILURE: "FETCH_MY_LIST_FAILURE",
  LOAD_MORE_MY_LIST_SUCCESS: "LOAD_MORE_MY_LIST_SUCCESS",

  CREATE_AND_REMOVE_MY_LIST_REQUEST: "CREATE_AND_REMOVE_MY_LIST_REQUEST",
  CREATE_MY_LIST_SUCCESS: "CREATE_MY_LIST_SUCCESS",
  CREATE_MY_LIST_FAILURE: "CREATE_MY_LIST_FAILURE",
  REMOVE_MY_LIST_SUCCESS: "REMOVE_MY_LIST_SUCCESS",
  REMOVE_MY_LIST_FAILURE: "REMOVE_MY_LIST_FAILURE",

  FETCH_FEATURED_MOVIES_REQUEST: "FETCH_FEATURED_MOVIES_REQUEST",
  FETCH_FEATURED_MOVIES_SUCCESS: "FETCH_FEATURED_MOVIES_SUCCESS",
  FETCH_FEATURED_MOVIES_FAILURE: "FETCH_FEATURED_MOVIES_FAILURE",
  LOAD_MORE_FEATURED_MOVIES_SUCCESS: "LOAD_MORE_FEATURED_MOVIES_SUCCESS",

  FETCH_TOP_TEN_MOVIES_REQUEST: "FETCH_TOP_TEN_MOVIES_REQUEST",
  FETCH_TOP_TEN_MOVIES_SUCCESS: "FETCH_TOP_TEN_MOVIES_SUCCESS",
  FETCH_TOP_TEN_MOVIES_FAILURE: "FETCH_TOP_TEN_MOVIES_FAILURE",
  LOAD_MORE_TOP_TEN_MOVIES_SUCCESS: "LOAD_MORE_TOP_TEN_MOVIES_SUCCESS",

  FETCH_LATEST_MOVIES_REQUEST: "FETCH_LATEST_MOVIES_REQUEST",
  FETCH_LATEST_MOVIES_SUCCESS: "FETCH_LATEST_MOVIES_SUCCESS",
  FETCH_LATEST_MOVIES_FAILURE: "FETCH_LATEST_MOVIES_FAILURE",
  LOAD_MORE_LATEST_MOVIES_SUCCESS: "LOAD_MORE_LATEST_MOVIES_SUCCESS",
};
